### PR TITLE
feat: add printer management component structure RP-63

### PR DESCRIPTION
**Pull request by Hosseinamir1989**
### Description
adding printer management component page that is serve Maas for managing the printers via adding ip address and ApiKey 

### Related Issue(s)
This project only accepts pull requests related to open issues. Don't forget to link to the issue(s) this pull request fixes.

### Type of Change
Replace the whitespace with an x in the boxes that apply

- [ ]  Bugfix
- [x]  New feature
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ]  This change requires a documentation update
- [ ]  Other (please describe):

### Checklist:
Go over all the following points, and replace the whitespace with an x in all the boxes that apply.

- [x]  I have performed a self-review of my own code
- [x]  I have commented my code in hard-to-understand areas
- [x]  I have made corresponding changes to the documentation
- [x]  My changes generate no new warnings
- [x]  New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mahlibalazs** [comment]
Could you add this description as a template later?

**Comment by mahlibalazs** [comment]
Resolved the conflict. ywc

**Comment by mahlibalazs** [comment]
Build failed, because of a missing comma. Added it in eaaed4224c9e0a976aac5379e357d0c0effc87fa

**Review by LostPersona — APPROVED** [review]
Seems valid to me.

**Pull request merged**
